import { IProject } from "@/interfaces/IProject";

export const Projects: IProject[] = [
  {
    title: "Miindset",
    description:
      " The world's first comprehensive app that helps improve your mental wellbeing.",
    imageUrl: "/assets/images/projects/miindset.png",
    technologies: [""],
    url: "https://web.hr/",
    layout: "responsive",
    imageWidth: "100",
    imageHight: "50",
  },
  {
    title: "WebHR",
    description: "Cloud Based All-in-One Social HR Software",
    imageUrl: "/assets/images/projects/webhr.jpg",
    technologies: [""],
    url: "https://web.hr/",
    layout: "responsive",
    imageWidth: "100",
    imageHight: "50",
  },
  {
    title: "SmartPupils",
    description: "Cloud Based All-in-One Social HR Software",
    imageUrl: "/assets/images/projects/smartpupils.png",
    technologies: [""],
    url: "https://web.hr/",
    layout: "responsive",
    imageWidth: "100",
    imageHight: "50",
  },
  {
    title: "HireSide",
    description: "Cloud Based All-in-One Social HR Software",
    imageUrl: "/assets/images/projects/hireside.png",
    technologies: [""],
    url: "https://web.hr/",
    layout: "responsive",
    imageWidth: "100",
    imageHight: "50",
  },
  {
    title: "Safco-E-credit",
    description: "Cloud Based All-in-One Social HR Software",
    imageUrl: "/assets/images/projects/safco.png",
    technologies: [""],
    imageWidth: "300",
    imageHight: "500",
    url: "/assets/images/projects/safco.png",
    layout: "intrinsic",
  },
];
